DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS BRANDS;
DROP TABLE IF EXISTS PRICES;

CREATE TABLE USERS (
  ID VARCHAR(250) AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(250) NOT NULL,
  PASSWORD VARCHAR(250) NOT NULL
);

CREATE TABLE BRANDS (
  BRAND_ID INT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);

CREATE TABLE PRICES (
  PRICE_ID INT AUTO_INCREMENT PRIMARY KEY,
  BRAND_ID INT NOT NULL,
  START_DATE TIMESTAMP NOT NULL,
  END_DATE TIMESTAMP NOT NULL,
  PRICE_LIST INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  PRIORITY INT NOT NULL,
  PRICE DOUBLE NOT NULL,
  CURR VARCHAR(10) NOT NULL,
  foreign key (BRAND_ID) references BRANDS(BRAND_ID)
);

INSERT INTO USERS (username, password)
    values ('prueba','prueba123');
INSERT INTO BRANDS (BRAND_ID, NAME) values (1,'ZARA');
INSERT INTO BRANDS (BRAND_ID, NAME) values (2,'PULL&BEAR');
INSERT INTO BRANDS (BRAND_ID, NAME) values (3,'MASSIMO DUTTI');
INSERT INTO BRANDS (BRAND_ID, NAME) values (4,'BERSHKA');
INSERT INTO BRANDS (BRAND_ID, NAME) values (5,'STRADIVARIUS');
INSERT INTO BRANDS (BRAND_ID, NAME) values (6,'OYSHO');
INSERT INTO BRANDS (BRAND_ID, NAME) values (7,'ZARA HOME');
INSERT INTO BRANDS (BRAND_ID, NAME) values (8,'UTERQUE');
INSERT INTO PRICES (BRAND_ID, START_DATE, END_DATE, PRICE_LIST, PRODUCT_ID, PRIORITY, PRICE, CURR)
    values (1,'2020-06-14 00.00.00','2020-12-31 23.59.59',1,35455,0,35.50,'EUR');
INSERT INTO PRICES (BRAND_ID, START_DATE, END_DATE, PRICE_LIST, PRODUCT_ID, PRIORITY, PRICE, CURR)
    values (1,'2020-06-14 15.00.00','2020-06-14 18.30.00',2,35455,1,25.45,'EUR');
INSERT INTO PRICES (BRAND_ID, START_DATE, END_DATE, PRICE_LIST, PRODUCT_ID, PRIORITY, PRICE, CURR)
    values (1,'2020-06-15 00.00.00','2020-06-15 11.00.00',3,35455,1,30.50,'EUR');
INSERT INTO PRICES (BRAND_ID, START_DATE, END_DATE, PRICE_LIST, PRODUCT_ID, PRIORITY, PRICE, CURR)
    values (1,'2020-06-15 16.00.00','2020-12-31 23.59.59',4,35455,1,38.95,'EUR');